franchise/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'(?P<project_id>\d+)?(/)?$', 'franchise.views.project_page', name='project'),
]

questory/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from questory import settings

urlpatterns = [
    url(r'^$', 'room.views.home_page', name="homepage"),
    url(r'^rooms/', include('room.urls', namespace="rooms")),               # rooms (room.urls) LIKE ARTICLES
    url(r'^projects/', include('franchise.urls', namespace="projects")),    # project page (franchise.urls) LIKE JOURNAL
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'account.views.login', name='login'),
    url(r'^logout/$', 'account.views.logout', name="logout"),
    url(r'^register/$', 'account.views.register', name="register"),
    url(r'^user/', include('account.urls', namespace="profiles")),
    url(r'^contact/$', 'account.views.contact_page', name="contact"),
    url(r'^about/$', 'account.views.about_page', name="about"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

room/urls.py
from django.conf.urls import url

from room.views import FavouriteRoomsView, VisitedRoomsView

urlpatterns = [
    url(r'^(?P<project_id>\d+)/(?P<room_id>\d+)?(/)?$', 'room.views.rooms_page', name='room'),
    url(r'^favourite/$', FavouriteRoomsView.as_view(), name='favourite'),
    url(r'^visited/$', VisitedRoomsView.as_view(), name='visited'),
    url(r'^favourite/remove/(?P<room_id>\d+)?(/)?$', 'room.views.remove_favourite_room', name='remove_favourite_room'),
    url(r'^visited/remove/(?P<room_id>\d+)?(/)?$', 'room.views.remove_visited_room', name='remove_visited_room'),
    url(r'^review/add/$', 'room.views.ajax_post_review', name="post_review"),
    url(r'^review/remove/$', 'room.views.ajax_remove_review', name="remove_review"),
]

room/models.py
import os

from django.contrib.auth.models import User
from django.db import models


def get_path(instance, filename):
    return os.path.join("rooms", instance.name, filename)


class Room(models.Model):
    class Meta:
        db_table = "room"
        verbose_name_plural = "rooms"

    image = models.ImageField(blank=True, upload_to=get_path)
    name = models.CharField(max_length=40)
    about = models.TextField(max_length=1000)
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    project = models.ForeignKey('franchise.Project', related_name="rooms_list", null=True)
    room_rating = models.ManyToManyField(User, through="RoomRating")

    def __unicode__(self):
        return "room name: %s (%s)" % (self.name, self.project.name)


class RoomRating(models.Model):
    class Meta:
        db_table = "room rating"
        verbose_name_plural = "room ratings"
        unique_together = ('user', 'room')

    user = models.ForeignKey(User, null=True)
    room = models.ForeignKey('Room', null=True)
    value = models.PositiveSmallIntegerField()

    def __unicode__(self):
        return "rating: %s (room %s(%s)) from user %s" % (
            self.value, self.room.name, self.room.project.name, self.user.username)

room/views.py
import random
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.http import HttpResponseRedirect as redirect
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import ListView

from account.forms import ReviewForm
from account.models import Review
from franchise.models import Project
from room.models import Room, RoomRating


def home_page(request):
    # TODO pagination of rooms
    rooms = Room.objects.all()
    # projects = Project.objects.all()
    slider_rooms = sorted(rooms.distinct(),
                          key=lambda x: random.random())[:10]
    return render(request, "room/homepage.html", {"rooms": rooms, "slider_rooms": slider_rooms})


@login_required(login_url="/login")
def rooms_page(request, project_id=None, room_id=None):
    if room_id is None and project_id is not None:
        # TODO pagination of articles
        project = Project.objects.get(id=project_id)
        project_rooms = Room.objects.filter(project=project)  # .order_by(RoomRating.value)
        # project_rooms = Project.objects.get(project__id=project_id).rooms_list.order_by(RoomRating.value)
        return render(request, "room/projectRooms.html", {"rooms": project_rooms})
    elif room_id is not None and project_id is not None:
        user = request.user
        form = ReviewForm()
        room = Room.objects.get(id=room_id)
        # TODO pagination of comments
        reviews = Review.objects.filter(room=room)
        try:
            room_rating = RoomRating.objects.get(user=user, room=room_id)  # of current user
        except RoomRating.DoesNotExist:
            room_rating = None
        if room is not None:
            return render(request, "room/roomPage.html",
                          {"room": room, "user": user, "room_rating": room_rating,
                           "review_form": form, "reviews": reviews})
        else:
            return HttpResponse("No such article!")
    else:
        # TODO
        pass


class FavouriteRoomsView(ListView):
    model = Room
    template_name = "room/favouriteRooms.html"

    @method_decorator(login_required(login_url="/login"))
    def dispatch(self, request, *args, **kwargs):
        return super(FavouriteRoomsView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(FavouriteRoomsView, self).get_context_data(**kwargs)
        context['favourite_rooms'] = Room.objects.filter(users_favour_list=self.request.user)
        return context


class VisitedRoomsView(ListView):
    model = Room
    template_name = "room/savedArticles.html"

    @method_decorator(login_required(login_url="/login"))
    def dispatch(self, request, *args, **kwargs):
        return super(VisitedRoomsView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(VisitedRoomsView, self).get_context_data(**kwargs)
        context['visited_rooms'] = Room.objects.filter(users_visit_list=self.request.user)
        return context


# TODO by AJAX
@login_required(login_url="/login")
def remove_favourite_room(request, room_id=None):
    user = request.user
    favourite_rooms = user.profile.favourite_rooms.all()
    if room_id is not None:
        room_to_delete = favourite_rooms.get(id=room_id)
        # < -- remove added in favour room for current user without deleting room model from database -- >
        user.profile.favourite_rooms.remove(room_to_delete)
    else:
        user.profile.favourite_rooms.clear()
    return redirect(reverse("rooms:favourite"))


# TODO by AJAX
@login_required(login_url="/login")
def remove_visited_room(request, room_id=None):
    user = request.user
    visited_rooms = user.profile.visited_rooms.all()
    if room_id is not None:
        room_to_delete = visited_rooms.get(id=room_id)
        # < -- remove added in visited room for current user without deleting room model from database -- >
        user.profile.visited_rooms.remove(room_to_delete)
    else:
        user.profile.visited_rooms.clear()
    return redirect(reverse("rooms:visited"))


@login_required(login_url="/login")
def ajax_post_review(request):
    user = request.user
    if request.method == "POST" and request.is_ajax():
        text = request.POST.get('text')
        room_id = request.POST.get('room_id')
        room = Room.objects.get(id=room_id)
        review = Review.objects.create(
            text=text,
            author=user,
            room=room,
            pub_date=datetime.now()
        )
        return render(request, "account/commentInclude.html", {"review": review})
    else:
        return render(request, "room/oneArticle.html")


@login_required(login_url="/login")
def ajax_remove_review(request):
    user = request.user
    if request.method == "POST" and request.is_ajax():
        review_id = request.POST.get('review_id')
        review = Review.objects.get(id=review_id)
        review.delete()
        return HttpResponse("ok")

room/templates/room/favouriteRooms.html
{% extends "base.html" %}

{# listutil - to view information from list in two columns #}
{#{% load listutil %}#}
{% load static %}

{% block links %}
{% endblock %}
{% block scripts %}
{% endblock %}
{% block conrent %}

    <b><a href="{% url 'articles:remove_saved_article' %}">remove all</a></b>

    {% if favourite_rooms %}
        {% for r in favourite_rooms %}
            <b><a href="{% url 'room:room(s)' r.id %}">{{ r.name }}</a></b> (<a
                href="{% url 'franchise:franchise(s)' r.project.id %}">{{ r.project.name }}</a>)<br/>
            {% if r.image %}
                <a href="{% url 'room:room(s)' r.id %}">
                    <img src="{{ r.image.url }}" height="200" width="200"/>
                </a>
            {% else %}
                <a href="{% url 'room:room(s)' r.id %}"><img
                        src="{% static 'images/article1.jpg' %}"></a>
            {% endif %}
            <p>{{ r.about|truncatechars:20 }}</p>
            <b><a href="{% url 'room:remove_favourite_room' r.id %}">remove</a></b>
            <b><a href="{% url 'franchise:franchise(s)' %}"> show all rooms of project {{ r.project.name }}</a></b>
            <hr/>
        {% endfor %}
    {% else %}
        No rooms yet..
    {% endif %}

{% endblock %}

room/templates/room/homepage.html
{% extends "base.html" %}

{% load static %}

{% block links %}
{% endblock %}
{% block scripts %}
{% endblock %}

{% block content %}
    <!-- SLIDER
================================================== -->
    <div id="ei-slider" class="ei-slider">
        <ul class="ei-slider-large">
            {% for room in slider_rooms %}
                <li>
                    {% if room.image %}
                        <a href="{% url 'rooms:room' room.project.id room.id %}">
                            <img src="{{ room.image.url }}"/>
                            {#    width="460" height="200    #}
                        </a>
                    {% else %}
                        <a href="{% url 'rooms:room' room.project.id room.id %}"><img
                                src="http://www.wowthemes.net/demo/studiofrancesca/images/slideshow/large/2.jpg" alt="">
                        </a>
                    {% endif %}
                    <div class="ei-title">
                        <h2>{{ room.name }}</h2>

                        <h3>{{ room.project.name }}</h3>
                    </div>
                </li>
            {% endfor %}
        </ul>
        <!-- slider-thumbs -->
        <ul class="ei-slider-thumbs">
            <li class="ei-slider-element">Current</li>
            {% for room in slider_rooms %}
                {% if room.image %}
                    <li><a href="{% url 'rooms:room' room.project.id room.id %}">
                        <img src="{{ room.image.url }}" class="slideshowthumb"/>
                    </a></li>
                {% else %}
                    <li><a href="#">Slide N</a><img src="http://placehold.it/150x59/444" class="slideshowthumb"/>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
    <div class="minipause">
    </div>
    <!-- SUBHEADER
    ================================================== -->
    <div id="subheader">
        <div class="row">
            <div class="twelve columns">
                <p class="text-center">
                     {#       WRITE HERE SOMETHING        #}
                </p>
            </div>
        </div>
    </div>
    <!-- CONTENT
    ================================================== -->
    <div class="row">
        <div class="twelve columns">
            <div class="centersectiontitle">
                <h4>What we do</h4>
            </div>
        </div>
        <div class="four columns">
            <h5>Photography</h5>

            <p>
                Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt
                ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.
            </p>

            <p>
                <a href="#" class="readmore">Learn more</a>
            </p>
        </div>
        <div class="four columns">
            <h5>Artwork</h5>

            <p>
                Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt
                ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.
            </p>

            <p>
                <a href="#" class="readmore">Learn more</a>
            </p>
        </div>
        <div class="four columns">
            <h5>Logos</h5>

            <p>
                Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt
                ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.
            </p>

            <p>
                <a href="#" class="readmore">Learn more</a>
            </p>
        </div>
    </div>
    <div class="hr">
    </div>
    <!-- TESTIMONIALS
    ================================================== -->
    <div class="row">
        <div class="twelve columns">
            <div id="testimonials">
                <blockquote>
                    <p>
                        "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                        laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
                        minim veniam, quis." <cite>Martin - NY</cite>
                    </p>
                </blockquote>
                <blockquote>
                    <p>
                        "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
                        pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
                        mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                        eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                        nostrud exercitation ullamco." <cite>Sandra - LA</cite>
                    </p>
                </blockquote>
                <blockquote>
                    <p>
                        "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
                        pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
                        mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                        eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                        nostrud exercitation ullamco." <cite>Jason - MA</cite>
                    </p>
                </blockquote>
            </div>
            <!--end testimonials-->
        </div>
    </div>
{% endblock %}

room/templates/room/projectRooms.html
{% extends "base.html" %}

{% load static %}

{% block content %}

    <!-- SUBHEADER
    ================================================== -->
    <div id="subheader">
        <div class="row">
            <div class="twelve columns">
                <p>
                    queStory Projects / <a href="{% url 'projects:project' rooms.first.project.id %}">
                    {{ rooms.first.project.name }}</a>
                </p>
            </div>
        </div>
    </div>
    <div class="hr">
    </div>
    <!-- CONTENT
    ================================================== -->
{#    <div class="row">#}
{#        <div class="twelve columns">#}
{#            <!-- CATEGORIES-->#}
{#            <section id="options" class="clearfix">#}
{#                <ul id="filters" class="option-set clearfix" data-option-key="filter">#}
{#                    <li><a href="#filter" data-option-value="*" class="portofoliobutton selected">Show all</a></li>#}
{#                    <li><a href="#filter" data-option-value=".nature" class="portofoliobutton">Last five</a></li>#}
{#                    <li><a href="#filter" data-option-value=".trains" class="portofoliobutton">show by rating</a></li>#}
{#                    <li><a href="#filter" data-option-value=".castles" class="portofoliobutton">Castles</a></li>#}
{#                </ul>#}
{#            </section>#}
{#        </div>#}
{#    </div>#}
    <div id="portofolio" class="row">
        {% for room in rooms %}
            <div class="six columns category trains">
                <h5>{{ room.name }}</h5>

                <p>
                    {{ room.about|truncatewords:20 }}
                </p>

                <div class="portofoliothumb">
                    <div class="portofoliothumboverlay">
                        <div class="viewgallery">
                            <!--image here -->
                            <a data-gal="prettyPhoto[gallery]"
                               href="http://www.wowthemes.net/demo/studiofrancesca/images/temp/folio1.jpg"><img
                                    src="http://www.wowthemes.net/demo/studiofrancesca/images/playgal.png"
                                    class="left galleryicon" alt=""> Gallery</a>
                        </div>
                        <div class="inner">
                            <a class="projectdetail" href="{% url 'rooms:room' room.project.id room.id %}">+ Room
                                Details</a>
                        </div>
                    </div>
                    <!-- image here -->
                    {% if room.image %}
                        <a href="{% url 'rooms:room' room.project.id room.id %}">
                            <img src="{{ room.image.url }}" width="460" height="200"/>
                        </a>
                    {% else %}
                        <a href="{% url 'projects:project' room.id %}"><img
                                src="http://www.wowthemes.net/demo/studiofrancesca/images/temp/folio1.jpg" alt="">
                        </a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="hr">
    </div>
{% endblock %}

room/templates/room/roomPage.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <!-- SUBHEADER
================================================== -->
    <div id="subheader">
        <div class="row">
            <div class="eight columns">
                <p>
                    <a href="{% url 'homepage' %}"> Home</a> /
                    <a href="{% url 'projects:project' room.project.id %}">{{ room.project.name }}</a>
                    / {{ room.name }}
                </p>
            </div>
            <div class="four columns">
                <div class="row collapse">
                    <div class="ten mobile-three columns">
                        <input type="text" class="nomargin" placeholder="Search...">
                    </div>
                    <div class="two mobile-one columns">
                        <a href="#" class="postfix button expand">Go</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="hr">
    </div>
    <!-- CONTENT
    ================================================== -->
    <div class="row">
        <div class="twelve columns noleftmargin">
            <!-- MAIN CONTENT -->
            <div class="eight columns">
                <div class="sectiontitle">
                    <h4>{{ room.name }}</h4>
                </div>
                <p>
                    {% if room.image %}
                        <a href="{% url 'rooms:room' room.project.id room.id %}">
                            <img src="{{ room.image.url }}"/>
                        </a>
                    {% else %}
                        <a href="{% url 'rooms:room' room.project.id room.id %}"><img
                                src="http://www.wowthemes.net/demo/studiofrancesca/images/temp/post.jpg"
                                class="blogimage grayscale" alt="">
                        </a>
                    {% endif %}
                </p>

                <p>
                    {{ room.about }}
                </p>
                <p>
                    <b>Address: {{ room.address }}</b></br>
                    <b>Phone:{{ room.phone }}</b>
                    {% if room_rating %}
                        <b>{{ room_rating.value }}</b>
                    {% endif %}
                </p>
                <br/>

                <div class="panel">
                    <div class="avatar">
                        <img src="http://www.wowthemes.net/demo/studiofrancesca/images/temp/author1.png" alt="">
                    </div>
                    <h5 class="left">AUTHOR: Jane Sanders </h5>

                    <div class="right">
                        <div class="social facebook">
                            <a href="#"></a>
                        </div>
                        <div class="social twitter">
                            <a href="#"></a>
                        </div>
                        <div class="social deviantart">
                            <a href="#"></a>
                        </div>
                        <div class="social flickr">
                            <a href="#"></a>
                        </div>
                        <div class="social dribbble">
                            <a href="#"></a>
                        </div>
                    </div>
                    <p class="clear authortext">
                        Jane is a professional photographer working for SLC. Temporibus autem quibusdam et aut officiis
                        debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae
                        non recusandae. Itaque earum rerum. <a href="#">Browse more articles</a> by this author.<br/>
                    </p>
                </div>
                <h5>1 Comment</h5>
                <hr>
                <div class="gravatar">
                    <img src="http://www.wowthemes.net/demo/studiofrancesca/images/gravatar.png" alt="">
                </div>
                <h5>Sam
			<span class="commentdate">
				- October 26, 2013 at 9:39 am
			</span>
                </h5>

                <p>
                    But she cuddled in bed with one knee up to her neck in cute boyish fashion, laughing softly at the
                    remembrance of another time when she had popped a cigarette stump into the eye of a London bobby
                    from the top of a bus. Temporibus autem quibusdam.
                </p>
                <br class="clear">
                <h5>SPEAK YOUR MIND</h5>
                <input type="text" class="five smoothborder" placeholder="Your name *"/>
                <input type="text" class="five smoothborder" placeholder="E-mail address *"/>
                <input type="text" class="five smoothborder" placeholder="Website"/>
                <textarea class="six smoothborder" rows="7" placeholder="Comments *"></textarea>
                <button type="submit" class="readmore">Publish</button>
            </div>
            <!-- SIDEBAR -->
            <div class="four columns">
                {#     TODO back link (where is it showld be situated?)    #}
                <h4><a href="{% url 'rooms:room' room.id %}"> [back to Project rooms] </a></h4>
                {#     TODO other rooms   #}
                <h6 class="sidebartitle">OTHER ROOMS OF PROJECT</h6>

                <div class="avatar">
                    <img src="http://www.wowthemes.net/demo/studiofrancesca/images/temp/author1.png" alt="">
                </div>
                <p>
                    Many pieces were proposed, but none seemed suitable, because each one wished to play a good ...
                </p>

                <div class="avatar">
                    <img src="http://www.wowthemes.net/demo/studiofrancesca/images/temp/author2.png" alt="">
                </div>
                <p>
                    Many pieces were proposed, but none seemed suitable, because each one wished to play a good ...
                </p>

                <div class="avatar">
                    <img src="http://www.wowthemes.net/demo/studiofrancesca/images/temp/author3.png" alt="">
                </div>
                <p>
                    Many pieces were proposed, but none seemed suitable, because each one wished to play a good ...
                </p>
                <br class="clear"/>
                <h6 class="sidebartitle">POPULAR TAGS</h6>
                <a href="#" class="tags">Photography</a>
                <a href="#" class="tags">Vintage</a>
                <a href="#" class="tags">Nature</a>
                <a href="#" class="tags">Design</a>
                <a href="#" class="tags">Printing</a>
                <a href="#" class="tags">Contemporary</a>
                <a href="#" class="tags">Classic</a>
                <a href="#" class="tags">Elegant</a>
                <a href="#" class="tags">Graphics</a>
                <br class="clear"/>
                <br/><br/>
                <h6 class="sidebartitle">RELATED POSTS</h6>

                <p>
                    7 Oct 2013
                </p>

                <p>
                    Many pieces were proposed, but none seemed suitable, because each one wished to play a good and
                    suitable part ...
                </p>

                <p>
                    6 Sept 2013
                </p>

                <p>
                    It was ready for production, when through accident we were disappointed about securing the private
                    theatre on ...
                </p>

                <p>
                    4 Aug 2013
                </p>

                <p>
                    The over-kind praise which it won encouraged me to have the play printed. I decided, as I could see
                    no other prospects...
                </p>
            </div>
        </div>
    </div>
    <div class="hr">
    </div>
{% endblock %}


{#{% if article %}#}
{#        <h3>{{ article.get_topic_display }}</h3>#}
{#        <b>{{ article.title }}</b><br/>#}
{#        {% if a.image %}#}
{#            <img src="{{ a.image.url }}" height="200" width="200"/>#}
{#        {% else %}#}
{#            <img src="{% static 'images/article1.jpg' %}">#}
{#        {% endif %}#}
{#        <p>{{ article.text }}</p>#}
{#        <p>{{ article.author.username }}</p>#}
{#        <p>{{ article.pub_date }}</p>#}
{#        <p>{{ article.journal.name }}</p> {# TODO href on journal page#}
{#        <br/>#}
{#        Tags:#}
{#        {% for tag in tags %}#}
{#            {{ tag.name }},#}
{#        {% endfor %}#}
{#        <br/>#}
{#        <p>Rating of an article from <b>{{ user.username }}<b/>: <b>{{ art_rating.value }}</b><p/>#}
{#        <hr/>#}
{#    {% else %}#}
{#        No article yet..#}
{#    {% endif %}#}
{#    <br/>#}
{#    <div class="secound_half">#}
{#        <div class="tags">#}
{#            <header>#}
{#                <h3 class="title-head">Tags</h3>#}
{#            </header>#}
{#            <p>#}
{#                {% for tag in tags %}#}
{#                    <a class="tag1" href="#">[{{ tag.name }}]</a>#}
{#                {% endfor %}#}
{#            </p>#}
{#        </div>#}
{#    </div>#}
{#    Comment:#}
{#    <form method="post" action="{% url 'comment' %}">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <input type="submit" value="Post a comment"/>#}
{#    </form>#}